user_activity/config/routes.rb
Rails.application.routes.draw do
  
  resources :activities 
  resources :users

  resources :user_sessions, only: [:create, :new, :destroy]

  get 'perfil/:id' => 'users#visit'

  root 'activities#index'

end

user_activity/app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :user
end

user_activity/app/models/user.rb
class User < ActiveRecord::Base

	has_many :activities, dependent: :nullify

	validates_presence_of :full_name, :email
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
	validates_uniqueness_of :email
	has_secure_password

	def self.authenticate(email, password)
		user = find_by(email: email).
		       try(:authenticate, password)
	end

end

user_activity/app/models/user_session.rb
class UserSession
	include ActiveModel::Model

	def initialize(session, attributes={})
		@session = session
		@email = attributes[:email]
		@password = attributes[:password]
	end

	attr_accessor :email, :password
	validates_presence_of :email, :password

	def authenticate!
		user = User.authenticate(@email, @password)

		if user.present?
			store(user)
		else
			errors.add(:base, 'Email ou Senha Invalida')
			false
		end

	end

	def store(user)
		@session[:user_id] = user.id
	end

	def current_user
		User.find(@session[:user_id])
	end

	def user_signed_in?
		@session[:user_id].present?
	end

	def destroy
		@session[:user_id] = nil
	end
end

user_activity/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :find_activity, only: [:edit, :update, :destroy] 
	before_action :require_authentication, only: [:new, :create, :edit, :update, :destroy]

	def index
		@activities = Activity.all.order('created_at DESC')
	end

	def show
		@activity = Activity.find(params[:id])
	end

	def new
		@activity = current_user.activities.build
	end

	def create
		@activity = current_user.activities.build(activity_params)

		if @activity.save
			redirect_to root_path, notice: "Postado com Sucesso!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update

		if @activity.update(activity_params)
			redirect_to @activity, notice: "Atualizado com Sucesso!"
		else
			render 'edit'
		end
	end

	def destroy
		@activity.destroy
		redirect_to root_path
	end
	
	private

	def activity_params
		params.require(:activity).permit(:description)
	end

	def find_activity
		# @activity = Activity.find(params[:id])
		@activity = current_user.activities.find(params[:id])
	end

end

user_activity/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	delegate :current_user, :user_signed_in?, to: :user_session

	# usar os metodos nos templates
	helper_method :current_user, :user_signed_in?

	def user_session
		UserSession.new(session)		
	end

	def require_authentication
		unless user_signed_in?
			redirect_to new_user_session_path, alert: "Você precisa está logado!"
		end
	end

	def require_no_authentication
		if user_signed_in?
			redirect_to root_path, notice: "Você ja está logado!"
		end
	end

end

user_activity/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :require_authentication, only: [:destroy]

	def new
		@user_session = UserSession.new(session)
	end

	def create
		@user_session = UserSession.new(session, user_session_params)

		if @user_session.authenticate!
			redirect_to root_path, notice: "Login realizado com Sucesso!"
		else
			render 'new'
		end
	end

	def destroy
		user_session.destroy
		redirect_to root_path, notice: "Você saiu. Até logo!"
	end

	private

	def user_session_params
		params.require(:user_session).permit(:email, :password)
	end
end

user_activity/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :update, :destroy, :index]
	before_action :require_no_authentication, only: [:new, :create]
	before_action :require_authentication, only: [:index, :show, :edit, :update, :destroy]
	before_action :can_change, only: [:edit, :update, :show]

	def index
	end

	def show
	end

	def visit
		@user_visit = find_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user, notice: "Cadrastro Realizado com Sucesso!"
		else
			render 'new'
		end
	end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: "Perfil Atualizado com Sucesso"
		else
			render 'new'
		end
	end

	def destroy
		@user.destroy
		user_session.destroy
		redirect_to root_path, notice: "Você excluiu sua conta."
	end

	private
	def user_params
		params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
	end

	def can_change
		unless user_signed_in? && current_user == find_user
			redirect_to user_path(current_user)
		end
	end

	def find_user
		@user = User.find(params[:id])
	end

end

user_activity/app/helpers/activities_helper.rb
module ActivitiesHelper
	def belogns_to_user(activity)
		user_signed_in? && activity.user == current_user
	end
end

user_activity/app/helpers/application_helper.rb
module ApplicationHelper
end

user_activity/app/helpers/users_helper.rb
module UsersHelper
end

user_activity/app/views/activities/_flash.html.haml
- flash.each do |name, msg|
	%div.alert.alert-info.alert-dismissible
		%button.close{'data-dismiss': "alert", 'aria-label': "Close"} 
			%span &times;
		= msg

user_activity/app/views/activities/_form.html.haml
= form_for @activity do |f|
	.form-group
		= f.text_area :description, class: 'form-control', rows: 10

	= f.submit 'Salvar', class: 'btn btn-primary'

user_activity/app/views/activities/edit.html.haml
.col-md-6.col-md-offset-3

	%h1 Editar Atividade

	= render 'form'

	%br
	= link_to root_path do
		%button.btn.btn-default Voltar

user_activity/app/views/activities/index.html.haml
%h1.text-center Bem Vindo!
%br
.col-md-8.col-md-offset-2

	= render 'flash'

	%ul.list-unstyled.list-activity
		- @activities.each do |activity|
			%li
				%div.description= truncate(activity.description, length: 200, separator: ' ', omission: '... (continuar)')
				%div
					- if activity.user 
						por: 
						= link_to activity.user.full_name, controller: "users", action: "visit", id: activity.user
					-else
						Sem Autor
					
				%div.created_at
					postado em: 
					= activity.created_at.strftime("%d %b %Y")
				%div.text-right
					%button.btn.btn-link= link_to "visualizar", activity

	= link_to new_activity_path do
		%button.btn.btn-default.pull-right Novo

	

	%br
	%br
	%br

user_activity/app/views/activities/new.html.haml
.col-md-6.col-md-offset-3

	%h1 Nova Atividade

	= render 'form'

	%br
	= link_to root_path do
		%button.btn.btn-default Voltar

user_activity/app/views/activities/show.html.haml
.col-md-6.col-md-offset-3
	%h2 Atividade:

	= render 'flash'

	%ul.list-unstyled.list-activity
		%li
			%div.description= @activity.description
			%div
				- if @activity.user 
					= @activity.user.full_name
				-else
					Sem Autor
				

			%div.created_at
				postado em: 
				= @activity.created_at.strftime("%d %b %Y")
			- if belogns_to_user(@activity)
				%div.text-right
					%button.btn.btn-link= link_to "Editar", edit_activity_path
					%button.btn.btn-link= link_to "Deletar", activity_path, method: :delete, data: {confirm: "Você tem certeza?"}

	= link_to root_path do
		%button.btn.btn-default Voltar

user_activity/app/views/activitys/new.html.haml
.col-md-6.col-md-offset-3

	%h1 Nova Atividade

	= render 'form'

	%br
	%button.btn.btn-default= link_to 'Voltar', root_path

user_activity/app/views/layouts/_signed_navbar.html.haml
.navbar-header.navbar-right
	= link_to 'Inicio', root_path, class: 'navbar-brand'
	= link_to 'Nova Postagem', new_activity_path, class: 'navbar-brand'
	= link_to 'Perfil', user_path(current_user), class: 'navbar-brand'
	= link_to 'Sair', user_session_path(current_user), method: :delete, class: 'navbar-brand'

user_activity/app/views/layouts/_visitor_navbar.html.haml
.navbar-header.navbar-right
	= link_to 'Inicio', root_path, class: 'navbar-brand'
	= link_to 'Login', new_user_session_path, class: 'navbar-brand'
	= link_to 'Novo', new_user_path, class: 'navbar-brand'

user_activity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Activity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= render 'layouts/signed_navbar' %>
    <% else %>
      <%= render 'layouts/visitor_navbar' %>
    <% end %>
  </div>
</nav>

<%= yield %>

</body>
</html>

user_activity/app/views/user_sessions/new.html.haml
%h1.text-center Login
%br
.col-md-4.col-md-offset-4

	

	= form_for @user_session do |f|
		.form-group
			= f.email_field :email, class: 'form-control input-lg', placeholder: 'seu@email.com', required: true
		.form-group
			= f.password_field :password, class: 'form-control input-lg', placeholder: 'senha', required: true

		= f.submit 'Logar', class: 'btn btn-lg btn-block btn-primary'

	%br
	- if @user_session.errors.has_key? :base
		%div.alert.alert-danger.alert-dismissible
			%button.close{'data-dismiss': "alert", 'aria-label': "Close"} 
				%span &times;
			= @user_session.errors[:base].join(', ')

user_activity/app/views/users/_form.html.haml
- if @user.errors.any?
	%div.alert.alert-danger.alert-dismissible
		%button.close{'data-dismiss': "alert", 'aria-label': "Close"} 
			%span &times;
		%div.text-center
			%strong Ops! alguma coisa deu errado:
		%ul
			- @user.errors.full_messages.each do |msg|
				%li= msg


= form_for @user do |f|
	.form-group
		= f.text_field :full_name, class: 'form-control input-lg', placeholder: 'Nome Usuário', required: true
	.form-group
		= f.email_field :email, class: 'form-control input-lg', placeholder: 'Email', required: true
	.form-group
		= f.password_field :password, class: 'form-control input-lg', placeholder: 'Senha'
	.form-group
		= f.password_field :password_confirmation, class: 'form-control input-lg', placeholder: 'Confirmar a Senha'

	= f.submit 'Salvar', class: 'btn btn-primary btn-block btn-lg'

user_activity/app/views/users/edit.html.haml
%h1.text-center Editar Perfil

.col-md-4.col-md-offset-4
	= render 'form'

user_activity/app/views/users/index.html.haml
%h1 Index usuario

user_activity/app/views/users/new.html.haml
%h1.text-center Novo Usuário

.col-md-4.col-md-offset-4
	%br
	= render 'form'

user_activity/app/views/users/show.html.haml
%h1.text-center= @user.full_name

.text-center= link_to "editar", edit_user_path
.text-center= link_to "excluir", @user, method: :delete, data: {confirm: "Você tem certeza que quer excluir sua conta?"}

.col-md-8.col-md-offset-2
	%ul.list-unstyled.list-activity
		- @user.activities.each do |activity|
			%li
				%div.description= truncate(activity.description, length: 200, separator: ' ', omission: '... (continuar)')
				%div
					por: 
					= link_to activity.user.full_name, controller: "users", action: "visit", id: activity.user
				%div.created_at
					postado em: 
					= activity.created_at.strftime("%d %b %Y")
				%div.text-right
					%button.btn.btn-link= link_to "visualizar", activity

user_activity/app/views/users/visit.html.haml
.text-center Visitando:
%h1.text-center= @user_visit.full_name
%h3.text-center Postagens:
%br
.col-md-8.col-md-offset-2
	%ul.list-unstyled.list-activity
		- @user.activities.each do |activity|
			%li
				%div.description= truncate(activity.description, length: 200, separator: ' ', omission: '... (continuar)')
				%div
					por: 
					= link_to activity.user.full_name, controller: "users", action: "visit", id: activity.user
				%div.created_at
					postado em: 
					= activity.created_at.strftime("%d %b %Y")
				%div.text-right
					%button.btn.btn-link= link_to "visualizar", activity